@ProcessingService_HostAddress = http://localhost:5035

POST {{ProcessingService_HostAddress}}/api/process
Content-Type: application/json

{
  "name": "Test",
  "value": 1,
  "metadata": {}
}
